import React, { createContext, useContext } from 'react';

const ModalIskContext = createContext();

export const useModalIskContext = () => {
  return useContext(ModalIskContext);
};

export default function ModalContext({ children }) {
  const rowsData = [
    {
      id: '1',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '2',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '3',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '4',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '5',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '6',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '7',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '8',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '9',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '10',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '11',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '12',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '13',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '14',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '15',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '16',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '17',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '18',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '19',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '20',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '21',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
    {
      id: '22',
      number: '№ 1326',
      date: '19.12.2023',
      plaintiff: 'Джумабеков Нурдин Арленович',
      defendant: 'Сейитбеков Тимур Сейитович',
      arbitrationFee: '0 валют',
      regulation: 'не выбран',
      arbitrators: 'Арбриты не назначены',
      secretary: 'Эльнура',
      status: 'Ответчик уведомлен',
      documentType: 'Определение об отказе иска',
    },
  ];

  console.log(children);
  return (
    <ModalIskContext.Provider value={{ rowsData }}>
      {children}
    </ModalIskContext.Provider>
  );
}
