name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 18.x]

    steps:
      - name: Get Code Repository
        uses: actions/checkout@master

      - name: Setup Nodejs
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: |
          CI=false npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Debug Source Directory
        run: |
          ls -la ${{ inputs.source }}

      - name: Copy Build to Server via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source:  '/home/runner/build/*'
          strip_components: 1
          target: "/mttp-site/build"
